### PR TITLE
Use TSC from its actual location

### PR DESCRIPTION
**Pull request by aciidb0mb3r**

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
Please test with following pull request:
https://github.com/apple/swift/pull/29723
https://github.com/apple/swift-package-manager/pull/2559

@swift-ci smoke test

**Comment by aciidb0mb3r** [comment]
Please test with following pull request:
https://github.com/apple/swift/pull/29723
https://github.com/apple/swift-package-manager/pull/2559

@swift-ci smoke test

**Comment by aciidb0mb3r** [comment]
Please test with following pull request:
https://github.com/apple/swift/pull/29723
https://github.com/apple/swift-package-manager/pull/2559

@swift-ci test

**Comment by benlangmuir** [comment]
How was it working before? Did we move it?

**Comment by benlangmuir** [comment]
This PR is out of date, and I put up a fresh one recently: https://github.com/apple/sourcekit-lsp/pull/305

**Pull request closed without merging**
