### PR TITLE
CODE_OF_CONDUCT

### PR DESCRIPTION
**Pull request by gaushikmr**

### CODE REVIEW

**Comment by benlangmuir** [comment]
sourcekit-lsp is under the same code of conduct as the rest of the Swift project: https://swift.org/community/#code-of-conduct. Rather than maintain a separate copy of the CoC in this repository, could we link to the one on Swift.org instead? 

```markdown
# Code of Conduct

The code of conduct for this project can be found at https://swift.org/community/#code-of-conduct
```

**Comment by gaushikmr** [comment]
@benlangmuir OK

**Comment by benlangmuir** [comment]
I was suggesting we link to it rather than copy - see my suggested wording in my previous comment.

**Comment by gaushikmr** [comment]
@benlangmuir just to link

**Comment by gaushikmr** [comment]
https://swift.org/community/#code-of-conduct

**Comment by benlangmuir** [comment]
Hi @gaushikmr, perhaps there was some confusion here. I was asking that we change the contents of CODE_OF_CONDUCT.md to 

```markdown
# Code of Conduct

The code of conduct for this project can be found at https://swift.org/community/#code-of-conduct
```

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@swift-ci please test

**Pull request merged**
