### PR TITLE
Only referesh semantic tokens if SourceKit returned semantic information

### PR DESCRIPTION
**Pull request by ahoppen**
In certain race condition scenarios, we might receive a document update to which the 0,0 replacetext request returned only syntactic information. In that case we shouldn’t update the sematnic syntax highlighting tokens.

The race condition rarely surfaced as a test failure of `testSemanticMultiEdit`.

CC @fwcd

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
Linux is failing because it’s running on Ubuntu 16.04 but Swift requires a more recent clang than installed on those machines. We need to wait until the CI job is updated to a more recent Ubuntu.

**Comment by ahoppen** [comment]
@swift-ci Please test Linux

**Review by benlangmuir — APPROVED** [review]

**Comment by fwcd** [comment]
Looks good to me, thanks for investigating this rare case! Do we get semantic information in a subsequent document update if this occurs?

**Comment by ahoppen** [comment]
Yes, we do, because [`testSemanticMultiEdit`](https://github.com/apple/sourcekit-lsp/blob/06df8239a0b6efeb3608f32bb262cd3f2a74a0c3/Tests/SourceKitLSPTests/SemanticTokensTests.swift#L673) always passed with this change and thus the document update with semantic information must have been delivered later on.

**Comment by ahoppen** [comment]
@swift-ci Please test Linux

**Comment by ahoppen** [comment]
@swift-ci Please test Linux

**Pull request merged**
