### PR TITLE
Fix CMake build not handling `@main` attribute

### PR DESCRIPTION
**Pull request by MaxDesiatov**
Looks like `@main` atttribute is not automatically recognized with CMake in executables that have a single source file declared.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Review by ahoppen — APPROVED** [review]
If you say so, I’m fine with this change. CC @compnerd

**Comment by compnerd** [comment]
I forgot about SR-12683.  An alternative is to pass `-parse-as-library`.

**Comment by MaxDesiatov** [comment]
Passing `-parse-as-library` for an executable feels very wrong to me. I personally prefer to rename it back to `main.swift`.

**Comment by ahoppen** [comment]
> Passing `-parse-as-library` for an executable feels very wrong to me. I personally prefer to rename it back to `main.swift`.

I agree

**Comment by MaxDesiatov** [comment]
Closing in favor of https://github.com/apple/sourcekit-lsp/pull/712

**Pull request closed without merging**
