### PR TITLE
Work on implementing dependenciesUpdated part of Build System integration

### PR DESCRIPTION
**Pull request by DavidGoldman**
See [this post](https://forums.swift.org/t/sourcekit-lsp-for-other-build-systems/27109/19), namely `workspace/dependenciesUpdated`

### CODE REVIEW

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by DavidGoldman** [comment]
Sounds good, I will go ahead and implement the changes for both sourcekitd and clangd and then work on adding some tests. I haven't gotten the tibs stuff working on my machine yet so I'll need to set that up.

**Comment by benlangmuir** [comment]
Need to regenerate linuxmain tests.  Otherwise LGTM

**Comment by DavidGoldman** [comment]
> Need to regenerate linuxmain tests. Otherwise LGTM

Done

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@swift-ci please test

**Pull request merged**
