### PR TITLE
Update for SwiftSyntax if/switch expression work

### PR DESCRIPTION
**Pull request by hamishknight**
Update for https://github.com/apple/swift-syntax/pull/1228

### CODE REVIEW

**Comment by hamishknight** [comment]
https://github.com/apple/swift-syntax/pull/1096

@swift-ci please test

**Comment by hamishknight** [comment]
https://github.com/apple/swift-syntax/pull/1096
https://github.com/apple/swift/pull/62178


@swift-ci please test

**Comment by hamishknight** [comment]
https://github.com/apple/swift-syntax/pull/1228
https://github.com/apple/swift/pull/62178


@swift-ci please test

**Comment by hamishknight** [comment]
https://github.com/apple/swift-syntax/pull/1228
https://github.com/apple/swift/pull/63022

@swift-ci please test

**Review by ahoppen — APPROVED** [review]

**Comment by hamishknight** [comment]
https://github.com/apple/swift-syntax/pull/1228
https://github.com/apple/swift/pull/63022

@swift-ci please test

**Comment by hamishknight** [comment]
https://github.com/apple/swift-syntax/pull/1228
https://github.com/apple/swift/pull/63022

@swift-ci please test

**Comment by hamishknight** [comment]
https://github.com/apple/swift-syntax/pull/1228
https://github.com/apple/swift/pull/63022

@swift-ci please test

**Pull request merged**
