### PR TITLE
Update SPM -> TSC module name prefixes

### PR DESCRIPTION
**Pull request by benlangmuir**
Updates to match apple/swift-package-manager#2325

### CODE REVIEW

**Comment by BenchR267** [comment]
Tested a build by changing the dependency in the Package.swift to match my development branch. Build and tests work. Thank you @benlangmuir! 

```Swift
-  .package(url: "https://github.com/apple/swift-package-manager.git", .branch("master")),
+  .package(url: "https://github.com/BenchR267/swift-package-manager.git", .branch("ben/tsc")),
```

**Comment by benlangmuir** [comment]
apple/swift-package-manager#2325

@swift-ci please test

**Comment by benlangmuir** [comment]
apple/swift-package-manager#2325

@swift-ci please test

**Comment by benlangmuir** [comment]
apple/swift-package-manager#2325

@swift-ci please test

**Comment by benlangmuir** [comment]
apple/swift-package-manager#2325

@swift-ci please test

**Pull request merged**
