### PR TITLE
Merge `main` into `release/6.0`

### PR DESCRIPTION
**Pull request by ahoppen**
Cherry-pick the following PRs to `release/6.0`

- https://github.com/apple/sourcekit-lsp/pull/1203
- https://github.com/apple/sourcekit-lsp/pull/1204
- https://github.com/apple/sourcekit-lsp/pull/1193
- https://github.com/apple/sourcekit-lsp/pull/1191
- https://github.com/apple/sourcekit-lsp/pull/1209
- https://github.com/apple/sourcekit-lsp/pull/1201

### CODE REVIEW

**Review by bnbarham — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/2637
https://github.com/apple/swift-package-manager/pull/7520

@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/2637
https://github.com/apple/swift-package-manager/pull/7520

@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/2637
https://github.com/apple/swift-package-manager/pull/7520

@swift-ci Please test Windows

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/73392
https://github.com/apple/swift-syntax/pull/2637
https://github.com/apple/swift-package-manager/pull/7520

@swift-ci Please test Windows

**Pull request merged**
