### PR TITLE
Format sources with swift-format

### PR DESCRIPTION
**Pull request by ahoppen**

### CODE REVIEW

**Comment by ahoppen** [comment]
Expected to fail because there are still two formatting issues.

https://github.com/apple/swift/pull/69516

@swift-ci Please test macOS

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/69516

@swift-ci Please test macOS

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/69516

@swift-ci Please test macOS

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/69516

@swift-ci Please test macOS

**Comment by ahoppen** [comment]
apple/swift#69516

@swift-ci Please test macOS

**Review by hamishknight — APPROVED** [review]

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/69516

@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/69516

@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/69516

@swift-ci Please test Windows

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/69516

@swift-ci Please test Windows

**Pull request merged**
