### PR TITLE
Don't call closeHandler if it is nil

### PR DESCRIPTION
**Pull request by AndreyKlebanov**
Issue: #852 closeHandler callback can be nil in an initializer

### CODE REVIEW

**Review by MaxDesiatov — COMMENTED** [review]
Would you be able to change `closeHandler`'s type to an explicit `?` optional type instead of `!` IOU? That way you can also write `await self.closeHandler?()` instead of doing a verbose `if self.closeHandler != nil` check.

**Review by MaxDesiatov — APPROVED** [review]
LGTM, thanks!

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Review by ahoppen — APPROVED** [review]
Thanks for fixing this so quickly after filing the issue 😄

**Comment by AndreyKlebanov** [comment]
@ahoppen My pleasure. Great project!

**Pull request merged**
