### PR TITLE
Merge `main` into `release/6.0`

### PR DESCRIPTION
**Pull request by ahoppen**
This adds the following PRs to `release/6.0`

- https://github.com/apple/sourcekit-lsp/pull/1151
- https://github.com/apple/sourcekit-lsp/pull/1170
- https://github.com/apple/sourcekit-lsp/pull/1187
- https://github.com/apple/sourcekit-lsp/pull/1186
- https://github.com/apple/sourcekit-lsp/pull/1190
- https://github.com/apple/sourcekit-lsp/pull/1176
- https://github.com/apple/sourcekit-lsp/pull/1185
- https://github.com/apple/sourcekit-lsp/pull/1188
- https://github.com/apple/sourcekit-lsp/pull/1192
- https://github.com/apple/sourcekit-lsp/pull/1183
- #1198
- #1200
- #1180
- #1175

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by bnbarham — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Pull request merged**
