### PR TITLE
Import `CRT` to resolve `free` on Windows

### PR DESCRIPTION
**Pull request by stevapple**
```
S:\sourcekit-lsp\Sources\SourceKitD\SKDResponse.swift:55:13: error: cannot find 'free' in scope
    defer { free(ptr) }
            ^~~~
S:\sourcekit-lsp\Sources\SourceKitD\SKDResponseArray.swift:65:13: error: cannot find 'free' in scope
    defer { free(ptr) }
            ^~~~
S:\sourcekit-lsp\Sources\SourceKitD\SKDRequestArray.swift:39:13: error: cannot find 'free' in scope
    defer { free(ptr) }
            ^~~~
S:\sourcekit-lsp\Sources\SourceKitD\SKDRequestDictionary.swift:64:13: error: cannot find 'free' in scope
    defer { free(ptr) }
            ^~~~
S:\sourcekit-lsp\Sources\SourceKitD\SKDResponseDictionary.swift:64:13: error: cannot find 'free' in scope
    defer { free(ptr) }
```

### CODE REVIEW

**Review by compnerd — APPROVED** [review]
Odd that we haven't hit this so far, but seems like a reasonable thing.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@stevapple how come this is not needed on Darwin btw?  I don't see an `import Darwn` here.

**Comment by stevapple** [comment]
@compnerd I didn’t figure out yet. It may share the same reason why we didn’t run into it before on Windows.

I guess this could be related with re-exported CStdlib symbols from some modules.

**Comment by compnerd** [comment]
Oh, it almost certainly is related to re-exporting.  But, it would be good to understand what's the root cause for the change in that.

**Comment by stevapple** [comment]
> But, it would be good to understand what's the root cause for the change in that.

May possibly be related to my fix on C header visibility… I opened this and apple/swift-corelibs-foundation#3151 as preparation to test that fix.

**Comment by ahoppen** [comment]
Windows noob question: Is `CRT` Window’s C standard library equivalent that defines `free` etc?

**Review by ahoppen — APPROVED** [review]
The change sounds reasonable to me and I trust @compnerd’s judgment that it makes sense from a Windows perspective.

**Pull request merged**
