### PR TITLE
[SwiftSyntax] Remove `Keyword` suffix from Pound*

### PR DESCRIPTION
**Pull request by kimdv**
Companion to https://github.com/apple/swift-syntax/pull/1862

### CODE REVIEW

**Comment by kimdv** [comment]
https://github.com/apple/swift-syntax/pull/1862

@swift-ci please test

**Comment by kimdv** [comment]
https://github.com/apple/swift-syntax/pull/1862

@swift-ci please test windows

**Comment by kimdv** [comment]
https://github.com/apple/swift-syntax/pull/1862

@swift-ci please test

**Comment by kimdv** [comment]
@ahoppen I think you need to merge this PR and https://github.com/apple/swift-syntax/pull/1862 as I don't have write access to this repo

**Comment by ahoppen** [comment]
Sure. Looks like https://github.com/apple/swift-syntax/pull/1862 needs a rebase though…

**Comment by kimdv** [comment]
https://github.com/apple/swift-syntax/pull/1862

@swift-ci please test

**Comment by kimdv** [comment]
https://github.com/apple/swift-syntax/pull/1862

@swift-ci please test

**Comment by kimdv** [comment]
https://github.com/apple/swift-syntax/pull/1862

@swift-ci please test

**Comment by kimdv** [comment]
https://github.com/apple/swift-syntax/pull/1862

@swift-ci please test

**Comment by kimdv** [comment]
https://github.com/apple/swift-syntax/pull/1862

@swift-ci please test windows

**Pull request merged**
