### PR TITLE
Add signposts for background preparation and indexing

### PR DESCRIPTION
**Pull request by ahoppen**
This allows nice visualization of the indexing progress in Instruments.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Review by hamishknight — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test macOS

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Pull request merged**
