### PR TITLE
[build-script-helper] Prefer just-built plugins to SDK plugins

### PR DESCRIPTION
**Pull request by rintaro**
Add '-Xswiftc -plugin-path -Xswiftc ${toolchain}/lib/swift/host/plugins' to swiftpm invocations.

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by rintaro** [comment]
@swift-ci Please test Windows

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by rintaro** [comment]
@swift-ci Please test Windows

**Comment by rintaro** [comment]
@swift-ci Please test Windows

**Comment by rintaro** [comment]
@swift-ci Please test Windows

**Comment by rintaro** [comment]
@swift-ci Please test Windows

**Review by bnbarham — APPROVED** [review]

**Pull request merged**
