### PR TITLE
Merge `main` into `release/6.0`

### PR DESCRIPTION
**Pull request by ahoppen**
Merge the following PRs into `release/6.0`:
- https://github.com/apple/sourcekit-lsp/pull/1450
- https://github.com/apple/sourcekit-lsp/pull/1453
- https://github.com/apple/sourcekit-lsp/pull/1451
- https://github.com/apple/sourcekit-lsp/pull/1455
- https://github.com/apple/sourcekit-lsp/pull/1462
- https://github.com/apple/sourcekit-lsp/pull/1472
- https://github.com/apple/sourcekit-lsp/pull/1474
- https://github.com/apple/sourcekit-lsp/pull/1473
- https://github.com/apple/sourcekit-lsp/pull/1460
- https://github.com/apple/sourcekit-lsp/pull/1447
- https://github.com/apple/sourcekit-lsp/pull/1467
- https://github.com/apple/sourcekit-lsp/pull/1459

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by bnbarham — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
Closing in favor of https://github.com/apple/sourcekit-lsp/pull/1477

**Pull request closed without merging**
