### PR TITLE
source_dir is str and UTF-8 already, python2, python3

### PR DESCRIPTION
**Pull request by soloturn**
make it work as well with python3 only, @gottesmm

### CODE REVIEW

**Comment by gottesmm** [comment]
Thanks @soloturn! I am going to kick off a test run.

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@soloturn ci.swift.org is down. When it is back, I'll redo the test.

**Comment by gottesmm** [comment]
@swift-ci  test

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
Testing installation via building a toolchain at https://github.com/apple/swift/pull/34436

**Pull request merged**
