### PR TITLE
Re-enable `SwiftInterfaceTests.testSystemModuleInterface`

### PR DESCRIPTION
**Pull request by ahoppen**
My hypothesis is that `testSystemModuleInterface` has been flaky because of a malformed global module cache that might still be present from previous CI runs. If we use a local module cache, we define away that source of bugs.
 
rdar://104871745

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by bnbarham — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please test macOS

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Pull request merged**
