### PR TITLE
[5.5] Bump swift-argument-parser to 0.4.1

### PR DESCRIPTION
**Pull request by neonichu**
Cherry pick of https://github.com/apple/sourcekit-lsp/pull/374

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
We need this for https://github.com/apple/swift-package-manager/pull/3473

**Review by benlangmuir — APPROVED** [review]

**Comment by benlangmuir** [comment]
https://github.com/apple/swift-package-manager/pull/3473
https://github.com/apple/swift-driver/pull/534

@swift-ci please test

**Comment by benlangmuir** [comment]
apple/swift-package-manager#3473
apple/swift-driver#628

@swift-ci please test

**Comment by neonichu** [comment]
apple/swift-package-manager#3473
apple/swift-driver#628

@swift-ci please test

**Review by akyrtzi — APPROVED** [review]

**Pull request merged**
