### PR TITLE
Move sourcekit-lsp off of SwiftPM's POSIX

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
SwiftPM's POSIX is going removed soon in order to make it more cross-platform. This removes all usage of POSIX from sourcekit-lsp.

<rdar://problem/49198341> Move sourcekit-lsp off of SwiftPM's POSIX

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by aciidb0mb3r** [comment]
@benlangmuir I can't trigger CI for some reason

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@aciidb0mb3r we don't have a smoke variant yet

**Comment by benlangmuir** [comment]
Hmm @shahmishal my test request is building ([macOS job](https://ci.swift.org/view/Pull%20Request/job/swift-sourcekit-lsp-PR-macOS/6) and [linux job](https://ci.swift.org/view/Pull%20Request/job/swift-sourcekit-lsp-PR-Linux/5)), but the status isn't showing up here on the PR.  Any ideas?

**Pull request merged**
