### PR TITLE
Update client capabilities to LSP 3.17

### PR DESCRIPTION
**Pull request by ahoppen**
Apparently, I only updated server capabilities and not client capabilities in https://github.com/apple/sourcekit-lsp/pull/671.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Review by bnbarham — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Pull request merged**
