### PR TITLE
Adopt the new location of vendored TSC in SwiftPM

### PR DESCRIPTION
**Pull request by aciidb0mb3r**

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
Please test with following pull request:
https://github.com/apple/swift-package-manager/pull/2637

@swift-ci test

**Comment by benlangmuir** [comment]
How does this relate to https://github.com/apple/sourcekit-lsp/pull/239, what's the goal here?

**Comment by aciidb0mb3r** [comment]
This is unrelated to that PR. This is allow to creating a Xcode workspace with SwiftPM and vendored TSC as the root packages.

**Comment by aciidb0mb3r** [comment]
It'll be moot after #239 but not sure when I'll get to it.

**Comment by aciidb0mb3r** [comment]
Please test with following pull request:
https://github.com/apple/swift-package-manager/pull/2637

@swift-ci test

**Pull request merged**
