### PR TITLE
[test] Add a test for SwiftPM integration

### PR DESCRIPTION
**Pull request by benlangmuir**
This goes through the work of building a swiftpm package, loading the
index, and performing requests against sourcekit-lsp using that package.
This gives us a canary test for our swiftpm support to make sure the
whole thing works together. We don't anticipate adding many tests like
this, since they are relatively slow.

### CODE REVIEW

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by aciidb0mb3r** [comment]
How long does it take to run this test? Will it make sense to move this to swift-integration-tests repo?

**Comment by benlangmuir** [comment]
I'm seeing around 3 seconds locally. Yeah, my intention is to do *something* like this in `swift-integration-tests` tests, but probably using the sourcekit-lsp binary instead of the library interfaces we go through for this test.

**Comment by benlangmuir** [comment]
Test failure is spurious; attempted fix in https://github.com/apple/indexstore-db/pull/36

**Comment by benlangmuir** [comment]
https://github.com/apple/indexstore-db/pull/36

@swift-ci please test

**Comment by benlangmuir** [comment]
apple/indexstore-db#36

@swift-ci please test

**Comment by benlangmuir** [comment]
apple/indexstore-db#36

@swift-ci please test

**Pull request merged**
