### PR TITLE
[5.6] Update dependency branches to release/5.6

### PR DESCRIPTION
**Pull request by ahoppen**

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by benlangmuir — APPROVED** [review]
Need to wait for https://github.com/apple/swift-package-manager/pull/3919 and https://github.com/apple/swift-driver/pull/929 to land first, but otherwise LGTM, thanks!

**Comment by ahoppen** [comment]
Do we really need to wait for those? Everything built fine for me locally with these changes applied.

**Comment by ahoppen** [comment]
The PRs in the package manager and driver have been merged and I got a successful local build + test using 
```
 ./Utilities/build-script-helper.py test --toolchain /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2021-12-23-a.xctoolchain/usr/ --no-local-deps
```

**Pull request merged**
