### PR TITLE
Implement "textDocument/rename" request

### PR DESCRIPTION
**Pull request by Trzyipolkostkicukru**
I'll write some test after I borrow a mac, meanwhile do you know if there is any documentation on what different `SymbolRole`s mean? I just blindly put all of them.

### CODE REVIEW

**Comment by benlangmuir** [comment]
Hi @Trzyipolkostkicukru,

I appreciate you taking the time to look at this.  Unfortunately, this is not going to behave correctly for argument labels, symbols that have different names across languages, or symbols that are involved in overrides or protocol conformances.  There are also ObjC-specific cases like renaming properties that have associated ivars.   Another consideration is that in addition to the existing LSP rename API, we're also interested in bringing the "live rename" functionality that we have in Xcode, and we'd like it to share as much of the implementation as possible with the LSP rename.

This is a case where I expect it would be much easier for me to port the rename code that we have internally, including its test suite, rather than reimplement it piecemeal from scratch.

**Comment by Trzyipolkostkicukru** [comment]
Oh no!

**Comment by Darrius4g** [comment]
Do what you gotta do

**Comment by Trzyipolkostkicukru** [comment]
By 'bringing the "live rename" functionality that we have in Xcode' do you mean adding a new unofficial request to the protocol?

**Comment by Darrius4g** [comment]
The name can be IsrarTv
An yes

**Comment by benlangmuir** [comment]
@Trzyipolkostkicukru yes, it would be an extension.

**Pull request closed without merging**
