### PR TITLE
Refactor FoldingRangeTests to use SKTibsTestWorkspace

### PR DESCRIPTION
**Pull request by rockbruno**
These tests were using the old way of opening files, but converting to `SKTibsTestWorkspace` will make extending this easier in the future.

### CODE REVIEW

**Comment by benlangmuir** [comment]
Ah, you need to update the linux test name (`swift test --generate-linuxmain`)

```
/home/buildnode/jenkins/workspace/swift-sourcekit-lsp-PR-Linux/sourcekit-lsp/Tests/SourceKitTests/XCTestManifests.swift:73:27: error: use of unresolved identifier 'testEmptyText'
         ("testEmptyText", testEmptyText),
                           ^~~~~~~~~~~~~
```

**Comment by rockbruno** [comment]
Sorry! Done.

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
@swift-ci please test Linux

**Pull request merged**
