### PR TITLE
[SKCore] If 'Platform.currentPlatform' is nil use 'so' as library extension

### PR DESCRIPTION
**Pull request by akyrtzi**
Platform only detects the 'debian' linux flavor so if it is nil it's most likely an unknown linux flavor

### CODE REVIEW

**Comment by pvieito** [comment]
`LinuxFlavor` should include an `unknown` case so when `Process.checkNonZeroExit(args: "uname")` returns `linux` we can at least return `.linux(. unknown)` in any case.

**Comment by akyrtzi** [comment]
> `LinuxFlavor` should include an `unknown` case so when `Process.checkNonZeroExit(args: "uname")` returns `linux` we can at least return `.linux(. unknown)` in any case.

That's a good idea but I think the change here is good to have regardless of your suggested improvement to `Platform`.
An unknown platform is more likely some unix-like platform, `.so` is a better fallback extension than `.dylib`.

**Comment by pvieito** [comment]
Ah, yes, of course!

**Comment by akyrtzi** [comment]
I'll tentatively merge this to allow the service to work on non-debian linux.

**Pull request merged**
