### PR TITLE
begin to integrate SwiftSystem

### PR DESCRIPTION
**Pull request by tomerd**
motivation: SwiftSystem provides infra that can replace some bespoke implementations in TSC and, improving the cross-platform support. as such we are adding it as a dependency to TSC

changes: add SwiftSystem to CMake setup so it can be included in CMake based builds

### CODE REVIEW

**Comment by tomerd** [comment]
cc compnerd

**Comment by tomerd** [comment]
related:
* apple/swift-system#73
* apple/swift-tools-support-core/pull/262
* apple/swift-package-manager/pull/3881

**Comment by tomerd** [comment]
cc @compnerd

**Comment by benlangmuir** [comment]
Is there a reason to add this to the cmake but not the Package.swift? The change itself seems fine.

**Review by benlangmuir — APPROVED** [review]

**Comment by tomerd** [comment]
swiftpm will bring it transitively: lsp -> swiftpm -> tsc -> system, so no needed to add explicitly

this change is only required for the cmake build of lsp

**Comment by tomerd** [comment]
https://github.com/apple/swift-package-manager/pull/3881
https://github.com/apple/swift-tools-support-core/pull/262
https://github.com/apple/swift-driver/pull/915

@swift-ci please test

**Comment by tomerd** [comment]
apple/swift-package-manager#3881
apple/swift-tools-support-core#262
apple/swift-driver#915

@swift-ci please test

**Pull request merged**
