### PR TITLE
NFC: add `.vscode/launch.json`

### PR DESCRIPTION
**Pull request by MaxDesiatov**
Submitted as an alternative to https://github.com/apple/sourcekit-lsp/pull/699.

Per @compnerd's comment:
> The workspace wide configuration should be portable, and allows us to add any recommended flags, which is convenient for getting started.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by adam-fowler** [comment]
This makes sense as the launch.json is the only file automatically created by the swift extension. 

As an aside it would be good to remove the tasks.json it gets in the way of the build tasks internally generated by the swift extension. I've found I can't build the release build of sourcekit-lsp because build task Cmd+Shift+B defaults to the debug build.

**Comment by MaxDesiatov** [comment]
> As an aside it would be good to remove the tasks.json

Ah, great catch! I didn't notice we had that one already...

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by ahoppen** [comment]
Since I’m not a big VSCode user myself, I leave it up to @adam-fowler to decide what is good practice to commit.

**Comment by adam-fowler** [comment]
This PR is good. Plus maybe remove the tasks.json

**Comment by MaxDesiatov** [comment]
@swift-ci test macOS

**Comment by MaxDesiatov** [comment]
@swift-ci test macOS

**Comment by MaxDesiatov** [comment]
@swift-ci test macOS

**Pull request merged**
