### PR TITLE
Create a `SwiftExtensions` module

### PR DESCRIPTION
**Pull request by ahoppen**
This allows us to share common Swift utility functions between SourceKit-LSP and LSPLogging.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by hamishknight — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Review by bnbarham — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Pull request merged**
