### PR TITLE
Teach `sourcekit-lsp diagnose` how to reduce `swift-frontend` crashes

### PR DESCRIPTION
**Pull request by ahoppen**
`sourcekit-lsp diagnose` tries to automatically scrape crash reports on the user’s machine for compiler arguments. If it finds any, it tries to reduce that swift-frontend crash.

Alternatively, a swift-frontend crash can be reduced by running 
```bash
sourcekit-lsp reduce-frontend [--toolchain /path/to/toolchain] --frontend-args -all -the frontend --args
```

rdar://124795084

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Review by bnbarham — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please test

**Pull request merged**
